---
# defaults file for libvirt-network
network_cidr: 192.168.123.0/24
networks:
  - name: libvirt
    bridge: virbr0
    forward_mode: nat
    address: "{{ network_cidr|nthhost(1) }}"
    netmask: "{{ network_cidr|ipaddr('netmask') }}"
    dhcp_range:
      - "{{ network_cidr|nthhost(10) }}"
      - "{{ network_cidr|nthhost(100) }}"
    nat_port_range:
      - 1024
      - 65535
