# Note: Some of the values in this config are missing as they are private credentails or subscription
# manager hashes.  This is to be used by humans only, not by CI.

release: pike
osp_release: rhos-12

undercloud_image_url: http://10.60.19.71/qcow2/undercloud.qcow2
overcloud_image_url: file:///usr/share/rhosp-director-images/overcloud-full.tar
ipa_image_url: file:///usr/share/rhosp-director-images/ironic-python-agent.tar

use_rhsm: false
rhel_version_number: 7
osp_release_version_number: 12
rhceph_version_number: 1.3

repo_cmd_before: |
  useradd stack
  echo "stack ALL=(root) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/stack
  sudo chmod 0440 /etc/sudoers.d/stack
  subscription-manager remove --all || true
  subscription-manager unregister || true
  rm -Rf /etc/yum.repos.d/*.repo
repo_cmd_after: |
  rm -Rf /etc/yum.repos.d/delorean*
  yum repolist
  yum clean all
  yum -y remove rhosp-director-images.noarch
  yum -y install rhosp-director-images.noarch
  md5sum /usr/share/rhosp-director-images/overcloud-full.tar > /usr/share/rhosp-director-images/overcloud-full.tar.md5
  md5sum /usr/share/rhosp-director-images/ironic-python-agent.tar > /usr/share/rhosp-director-images/ironic-python-agent.tar.md5

repos:
  - type: file
    filename: rhos.repos
    down_url: http://10.60.19.71/puddle

undercloud_setup: true
skip_build_images: true
selinux_enforcing: true
non_root_user_setup: true
package_installs: true
hostname_correction: true
baseos_as_undercloud: true
repo_run_live: false
